import torch
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    pipeline,
    logging,
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from datasets import load_dataset
from trl import SFTTrainer
import os

# 1. Configuration
model_id = "meta-llama/Meta-Llama-3-8B"
dataset_path = "C:/Users/senth/.gemini/antigravity/brain/9a5a993d-1470-428b-bbf7-ddde52892667/legal_dataset.jsonl"
output_dir = "./legal-gpt-llama3-adapter"

# 2. QLoRA Config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

# 3. Load Model & Tokenizer
print(f"Loading {model_id}...")
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True
)
model.config.use_cache = False
model = prepare_model_for_kbit_training(model)

tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

# 4. LoRA Config
lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"], # Llama-3 standard
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)
model = get_peft_model(model, lora_config)

# 5. Dataset Loading
dataset = load_dataset('json', data_files=dataset_path, split='train')

def formatting_func(example):
    # The 'output' field already contains the full chat format generated by generate_legal_data.py
    return example['output']

# 6. Training Arguments
training_args = TrainingArguments(
    output_dir=output_dir,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    max_steps=100, # Increased for better grounding
    logging_steps=10,
    save_steps=50,
    fp16=True,
    optim="paged_adamw_8bit"
)

# 7. SFT Trainer
trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    peft_config=lora_config,
    max_seq_length=1024,
    tokenizer=tokenizer,
    args=training_args,
    packing=False,
    dataset_text_field="output", # Using the pre-formatted output field
)

print("Starting Fine-Tuning...")
trainer.train()

# 8. Save Weights
trainer.model.save_pretrained(output_dir)
print(f"✅ Training complete. Adapters saved to {output_dir}")
